var fs = require('fs')
var vm = require('vm')

// all paths here are relative to the project root
// at least where npm is run from the project root

var import_file = (path) => {
  try {
    var code = fs.readFileSync(path)
    vm.runInThisContext(code)  
  } catch(err) {
    console.error('FAILURE', path)
    throw err
  }
}

import_file("src/lib/xregexp-all/xregexp-all.js")
import_file("src/lib/closure-library/closure/goog/base.js")

global.window = {}
global.document = process

// DO NOT EDIT NEXT LINE
// DYNAMIC DEPS START
import_file("src/lib/closure-library/closure/goog/color/color.js")
import_file("src/lib/closure-library/closure/goog/useragent/useragent.js")
import_file("src/lib/eyo/js/core/eyo.js")
import_file("src/lib/eyo/Include/errcode.js")
import_file("src/lib/eyo/js/core/const.js")
import_file("src/lib/eyo/js/core/const.js")
import_file("src/lib/eyo/js/core/decorate.js")
import_file("src/lib/eyo/js/core/do.js")
import_file("src/lib/eyo/js/core/model.js")
import_file("src/lib/eyo/js/core/setup.js")
import_file("src/lib/eyo/js/core/xre.js")
import_file("src/lib/eyo/js/msg/base.js")
import_file("src/lib/eyo/js/core/c9r.js")
import_file("src/lib/eyo/js/core/attr.js")
import_file("src/lib/eyo/js/core/t3.js")
import_file("src/lib/eyo/js/other/db.js")
import_file("src/lib/eyo/js/py/py.js")
import_file("src/lib/closure-library/closure/goog/dom/dom.js")
import_file("src/lib/eyo/js/core/p6y.js")
import_file("src/lib/eyo/js/core/t3_all.js")
import_file("src/lib/eyo/js/py/bitset.js")
import_file("src/lib/eyo/js/py/grammar.js")
import_file("src/lib/eyo/js/py/node.js")
import_file("src/lib/eyo/js/py/node.js")
import_file("src/lib/eyo/js/py/token.js")
import_file("src/lib/closure-library/closure/goog/dom/xml.js")
import_file("src/lib/eyo/Python/graminit.js")
import_file("src/lib/eyo/js/application/desk/board/brick/brick_util/node_brick.js")
import_file("src/lib/eyo/js/core/o4t.js")
import_file("src/lib/eyo/js/core/register.js")
import_file("src/lib/closure-library/closure/goog/style/style.js")
import_file("src/lib/eyo/js/core/change_count.js")
import_file("src/lib/eyo/js/core/data.js")
import_file("src/lib/eyo/js/core/data.js")
import_file("src/lib/eyo/js/core/geometry.js")
import_file("src/lib/eyo/js/core/geometry.js")
import_file("src/lib/eyo/js/core/geometry.js")
import_file("src/lib/eyo/js/core/o3d.js")
import_file("src/lib/eyo/js/py/parser.js")
import_file("src/lib/eyo/js/application/desk/board/brick/brick_util/consolidator.js")
import_file("src/lib/eyo/js/application/desk/board/brick/dfs.js")
import_file("src/lib/eyo/js/application/desk/board/brick/span.js")
import_file("src/lib/eyo/js/application/desk/board/metrics/metrics.js")
import_file("src/lib/eyo/js/application/desk/workspace/flyout/section.js")
import_file("src/lib/eyo/js/application/ui/audio.js")
import_file("src/lib/eyo/js/application/ui/dnd.js")
import_file("src/lib/eyo/js/application/ui/dnd.js")
import_file("src/lib/eyo/js/core/changer.js")
import_file("src/lib/eyo/js/core/event.js")
import_file("src/lib/eyo/js/core/event.js")
import_file("src/lib/eyo/js/core/event.js")
import_file("src/lib/eyo/js/core/font.js")
import_file("src/lib/eyo/js/core/view.js")
import_file("src/lib/eyo/js/core/view.js")
import_file("src/lib/eyo/js/module/module.js")
import_file("src/lib/eyo/js/module/module.js")
import_file("src/lib/eyo/js/other/dragger.js")
import_file("src/lib/eyo/js/py/tokenizer.js")
import_file("src/lib/eyo/js/application/abstract/bsm_o3d.js")
import_file("src/lib/eyo/js/application/abstract/control.js")
import_file("src/lib/eyo/js/application/app.js")
import_file("src/lib/eyo/js/application/desk/board/board.js")
import_file("src/lib/eyo/js/application/desk/board/brick/brick_util/brick_events.js")
import_file("src/lib/eyo/js/application/desk/desk.js")
import_file("src/lib/eyo/js/application/desk/graphic/graphic.js")
import_file("src/lib/eyo/js/application/desk/template/template.js")
import_file("src/lib/eyo/js/application/desk/terminal/terminal.js")
import_file("src/lib/eyo/js/application/desk/turtle/turtle.js")
import_file("src/lib/eyo/js/application/desk/variable/variable.js")
import_file("src/lib/eyo/js/application/desk/workspace/flyout/draft.js")
import_file("src/lib/eyo/js/application/desk/workspace/flyout/flyout.js")
import_file("src/lib/eyo/js/application/desk/workspace/flyout/flyout.js")
import_file("src/lib/eyo/js/application/desk/workspace/flyout/search.js")
import_file("src/lib/eyo/js/application/desk/workspace/scrollbar/scrollbar.js")
import_file("src/lib/eyo/js/application/desk/workspace/scroller/scroller.js")
import_file("src/lib/eyo/js/application/desk/workspace/workspace.js")
import_file("src/lib/eyo/js/application/driver/driver.js")
import_file("src/lib/eyo/js/application/ui/motion.js")
import_file("src/lib/eyo/js/core/ui.js")
import_file("src/lib/eyo/js/core/ui.js")
import_file("src/lib/eyo/js/module/module_decimal.js")
import_file("src/lib/eyo/js/module/module_functions.js")
import_file("src/lib/eyo/js/module/module_math.js")
import_file("src/lib/eyo/js/module/module_random.js")
import_file("src/lib/eyo/js/module/module_stdtypes.js")
import_file("src/lib/eyo/js/module/module_turtle.js")
import_file("src/lib/eyo/js/module/profile.js")
import_file("src/lib/eyo/js/other/scaler.js")
import_file("src/lib/eyo/js/application/desk/board/brick/brick.js")
import_file("src/lib/eyo/js/application/desk/board/brick/brick.js")
import_file("src/lib/eyo/js/application/desk/board/brick/field/field.js")
import_file("src/lib/eyo/js/application/desk/board/brick/field/field.js")
import_file("src/lib/eyo/js/application/desk/board/brick/field/field.js")
import_file("src/lib/eyo/js/application/desk/board/brick/magnet/magnet.js")
import_file("src/lib/eyo/js/application/desk/board/brick/magnet/magnet.js")
import_file("src/lib/eyo/js/application/desk/board/brick/slot/slot.js")
import_file("src/lib/eyo/js/application/desk/workspace/flyout/flyout-toolbar.js")
import_file("src/lib/eyo/js/application/desk/workspace/trashcan/trashcan.js")
import_file("src/lib/eyo/js/application/desk/workspace/zoomer/zoomer.js")
import_file("src/lib/eyo/js/application/driver/fcls/fcls.js")
import_file("src/lib/eyo/js/application/ui/css.js")
import_file("src/lib/eyo/js/application/desk/board/brick/list.js")
import_file("src/lib/eyo/js/application/desk/focus.js")
import_file("src/lib/eyo/js/application/driver/fcfl/fcfl.js")
import_file("src/lib/eyo/js/application/driver/fcls/fcls_brick.js")
import_file("src/lib/eyo/js/brick_py/stmt.js")
import_file("src/lib/eyo/js/other/tooltip.js")
import_file("src/lib/eyo/js/application/desk/board/brick/brick_util/navigate.js")
import_file("src/lib/eyo/js/application/desk/workspace/flyout/library.js")
import_file("src/lib/eyo/js/application/driver/dom/dom.js")
import_file("src/lib/eyo/js/brick_py/expr.js")
import_file("src/lib/eyo/js/brick_py/group.js")
import_file("src/lib/eyo/js/application/driver/dom/dom_brick.js")
import_file("src/lib/eyo/js/application/driver/dom/dom_desk.js")
import_file("src/lib/eyo/js/application/driver/dom/dom_flyout.js")
import_file("src/lib/eyo/js/application/driver/dom/dom_search.js")
import_file("src/lib/eyo/js/application/driver/svg/svg.js")
import_file("src/lib/eyo/js/brick_py/list.js")
import_file("src/lib/eyo/js/brick_py/operator.js")
import_file("src/lib/eyo/js/brick_py/range.js")
import_file("src/lib/eyo/js/brick_py/starred.js")
import_file("src/lib/eyo/js/application/driver/svg/svg_brick.js")
import_file("src/lib/eyo/js/application/driver/svg/svg_field.js")
import_file("src/lib/eyo/js/application/driver/svg/svg_slot.js")
import_file("src/lib/eyo/js/brick_py/assignment.js")
import_file("src/lib/eyo/js/brick_py/primary.js")
import_file("src/lib/eyo/js/application/desk/board/brick/brick_util/xml.js")
import_file("src/lib/eyo/js/application/desk/board/brick/model/brick_cmath.js")
import_file("src/lib/eyo/js/application/desk/board/brick/model/brick_decimal.js")
import_file("src/lib/eyo/js/application/desk/board/brick/model/brick_fractions.js")
import_file("src/lib/eyo/js/application/desk/board/brick/model/brick_functions.js")
import_file("src/lib/eyo/js/application/desk/board/brick/model/brick_math.js")
import_file("src/lib/eyo/js/application/desk/board/brick/model/brick_random.js")
import_file("src/lib/eyo/js/application/desk/board/brick/model/brick_statistics.js")
import_file("src/lib/eyo/js/application/desk/board/brick/model/brick_stdtypes.js")
import_file("src/lib/eyo/js/application/desk/board/brick/model/brick_turtle.js")
// DYNAMIC DEPS END
