// This file was generated by "python types.py" on 2018-05-08 19:58:06.959503

/**
 * ezPython
 *
 * Copyright 2018 Jérôme LAURENS.
 *
 * License CeCILL-B
 */
/**
 * @fileoverview Type constants for ezPython, used as blocks prototypes.
 * @author jerome.laurens@u-bourgogne.fr (Jérôme LAURENS)
 */
'use strict'

/**
 * @name edY.T3.All
 * @namespace
 **/

goog.provide('edY.T3.All')

goog.require('edY.T3')


edY.T3.All = {}
edY.T3.All.core_expressions = [ // count 75
    edY.T3.Expr.a_expr_s3d,
    edY.T3.Expr.and_expr_s3d,
    edY.T3.Expr.and_test_s3d,
    edY.T3.Expr.any,
    edY.T3.Expr.argument_list,
    edY.T3.Expr.attributeref,
    edY.T3.Expr.augop,
    edY.T3.Expr.bracket_target_list,
    edY.T3.Expr.builtin_input_expr,
    edY.T3.Expr.builtin_object,
    edY.T3.Expr.builtin_print_expr,
    edY.T3.Expr.call_expr,
    edY.T3.Expr.call_expr,
    edY.T3.Expr.comp_for,
    edY.T3.Expr.comp_if,
    edY.T3.Expr.comprehension,
    edY.T3.Expr.conditional_expression_s3d,
    edY.T3.Expr.defparameter_s3d,
    edY.T3.Expr.dict_comprehension,
    edY.T3.Expr.dict_display,
    edY.T3.Expr.expression_star,
    edY.T3.Expr.expression_star_star,
    edY.T3.Expr.floatnumber,
    edY.T3.Expr.identifier,
    edY.T3.Expr.imagnumber,
    edY.T3.Expr.import_identifier_as_s3d,
    edY.T3.Expr.inheritance,
    edY.T3.Expr.integer,
    edY.T3.Expr.key_datum_s3d,
    edY.T3.Expr.keyword_item,
    edY.T3.Expr.lambda,
    edY.T3.Expr.lambda_expr,
    edY.T3.Expr.lambda_expr_nocond,
    edY.T3.Expr.list_display,
    edY.T3.Expr.longbytesliteral,
    edY.T3.Expr.longformattedliteral,
    edY.T3.Expr.longstringliteral,
    edY.T3.Expr.m_expr_s3d,
    edY.T3.Expr.module_as_s3d,
    edY.T3.Expr.non_void_expression_list,
    edY.T3.Expr.not_test_s3d,
    edY.T3.Expr.number_comparison,
    edY.T3.Expr.object_comparison,
    edY.T3.Expr.optional_expression_list,
    edY.T3.Expr.or_expr_s3d,
    edY.T3.Expr.or_expr_star_star,
    edY.T3.Expr.or_test_s3d,
    edY.T3.Expr.parameter_list,
    edY.T3.Expr.parameter_list_starargs,
    edY.T3.Expr.parameter_s3d,
    edY.T3.Expr.parameter_star,
    edY.T3.Expr.parameter_star_star,
    edY.T3.Expr.parent_module,
    edY.T3.Expr.parenth_form,
    edY.T3.Expr.parenth_target_list,
    edY.T3.Expr.power_s3d,
    edY.T3.Expr.proper_slice,
    edY.T3.Expr.set_display,
    edY.T3.Expr.shift_expr_s3d,
    edY.T3.Expr.shortbytesliteral,
    edY.T3.Expr.shortformattedliteral,
    edY.T3.Expr.shortstringliteral,
    edY.T3.Expr.slicing,
    edY.T3.Expr.star_expr,
    edY.T3.Expr.starred_expression,
    edY.T3.Expr.starred_item_list,
    edY.T3.Expr.subscription,
    edY.T3.Expr.target_list_list,
    edY.T3.Expr.target_star,
    edY.T3.Expr.term,
    edY.T3.Expr.u_expr_s3d,
    edY.T3.Expr.void_target_list,
    edY.T3.Expr.with_item_s3d,
    edY.T3.Expr.xor_expr_s3d,
    edY.T3.Expr.yield_expression,
]
edY.T3.All.lists = [ // count 10
    edY.T3.Expr.comp_iter_list,
    edY.T3.Expr.dotted_name,
    edY.T3.Expr.key_datum_list,
    edY.T3.Expr.non_void_identifier_list,
    edY.T3.Expr.non_void_import_identifier_as_list,
    edY.T3.Expr.non_void_module_as_list,
    edY.T3.Expr.non_void_starred_item_list,
    edY.T3.Expr.slice_list,
    edY.T3.Expr.target_list,
    edY.T3.Expr.with_item_list,
]
edY.T3.All.wrappers = [ // count 50
    edY.T3.Expr.a_expr,
    edY.T3.Expr.algebra_choice,
    edY.T3.Expr.and_expr,
    edY.T3.Expr.and_test,
    edY.T3.Expr.argument_any,
    edY.T3.Expr.argument_list_comprehensive,
    edY.T3.Expr.assigned_list,
    edY.T3.Expr.atom,
    edY.T3.Expr.augassigned_list,
    edY.T3.Expr.augtarget,
    edY.T3.Expr.bitwise_choice,
    edY.T3.Expr.boolean_choice,
    edY.T3.Expr.bytesliteral,
    edY.T3.Expr.comp_iter,
    edY.T3.Expr.comparison,
    edY.T3.Expr.conditional_expression,
    edY.T3.Expr.defparameter,
    edY.T3.Expr.enclosure,
    edY.T3.Expr.expression,
    edY.T3.Expr.expression_nocond,
    edY.T3.Expr.import_identifier_as,
    edY.T3.Expr.key_datum,
    edY.T3.Expr.key_datum_list_comprehensive,
    edY.T3.Expr.literal,
    edY.T3.Expr.longliteral,
    edY.T3.Expr.m_expr,
    edY.T3.Expr.module,
    edY.T3.Expr.module_as,
    edY.T3.Expr.non_void_starred_item_list_comprehensive,
    edY.T3.Expr.not_test,
    edY.T3.Expr.numberliteral,
    edY.T3.Expr.or_expr,
    edY.T3.Expr.or_test,
    edY.T3.Expr.parameter,
    edY.T3.Expr.parameter_any,
    edY.T3.Expr.power,
    edY.T3.Expr.primary,
    edY.T3.Expr.relative_module,
    edY.T3.Expr.shift_expr,
    edY.T3.Expr.shortliteral,
    edY.T3.Expr.slice_item,
    edY.T3.Expr.starred_item,
    edY.T3.Expr.starred_item_list_comprehensive,
    edY.T3.Expr.stringliteral,
    edY.T3.Expr.target,
    edY.T3.Expr.target_unstar,
    edY.T3.Expr.u_expr,
    edY.T3.Expr.unary_choice,
    edY.T3.Expr.with_item,
    edY.T3.Expr.xor_expr,
]
edY.T3.All.part_statements = [ // count 14
    edY.T3.Stmt.classdef_part,
    edY.T3.Stmt.elif_part,
    edY.T3.Stmt.else_part,
    edY.T3.Stmt.except_part,
    edY.T3.Stmt.finally_part,
    edY.T3.Stmt.for_part,
    edY.T3.Stmt.funcdef_part,
    edY.T3.Stmt.if_part,
    edY.T3.Stmt.last_else_part,
    edY.T3.Stmt.try_else_part,
    edY.T3.Stmt.try_part,
    edY.T3.Stmt.void_except_part,
    edY.T3.Stmt.while_part,
    edY.T3.Stmt.with_part,
]
edY.T3.All.simple_statements = [ // count 14
    edY.T3.Stmt.classdef_part,
    edY.T3.Stmt.elif_part,
    edY.T3.Stmt.else_part,
    edY.T3.Stmt.except_part,
    edY.T3.Stmt.finally_part,
    edY.T3.Stmt.for_part,
    edY.T3.Stmt.funcdef_part,
    edY.T3.Stmt.if_part,
    edY.T3.Stmt.last_else_part,
    edY.T3.Stmt.try_else_part,
    edY.T3.Stmt.try_part,
    edY.T3.Stmt.void_except_part,
    edY.T3.Stmt.while_part,
    edY.T3.Stmt.with_part,
]
edY.T3.All.compound_statements = [ // count 0
]

edY.T3.All.containsStatement = function(prototypeName) {
  return edY.T3.All.part_statements.indexOf(prototypeName)>=0
  || edY.T3.All.simple_statements.indexOf(prototypeName)>=0
  || edY.T3.All.compound_statements.indexOf(prototypeName)>=0
}

edY.T3.All.containsExpression = function(prototypeName) {
  return edY.T3.All.core_expressions.indexOf(prototypeName)>=0
  || edY.T3.All.lists.indexOf(prototypeName)>=0
  || edY.T3.All.wrappers.indexOf(prototypeName)>=0
}

edY.T3.All.contains = function(type) {
  return edY.T3.All.containsStatement(prototypeName)
  || edY.T3.All.containsExpression(prototypeName)
}

