// This file was generated by "update.py" on 2020-09-26 09:37:50.755101

//  /**
//   * @fileoverview Fcls utils. Some code specific to flyout and desk.
//   * @author jerome.laurens@u-bourgogne.fr
//   */
//  'use strict'
//  
//  /**
//   * @name {eYo.fcls}
//   * @namespace
//   */
//  eYo.drvr.newNS(eYo, 'fcls')
//  
describe(`Inline tests at drvr/fcls/fcls.js`, function () {
  this.timeout(20000)
  beforeEach (function () { eYo.test.setup() })
  eYo.test.onrModel = eYo.NA
  eYo.test.setup()
  it(`eYo.fcls`, function () {
    chai.assert(eYo.fcls)
  })

})
