// This file was generated by "update.py" on 2020-09-26 09:37:50.756605

//  /**
//   * @fileoverview Rendering delegate. Do nothing driver.
//   * @author jerome.laurens@u-bourgogne.fr (Jérôme LAURENS)
//   */
//  'use strict'
//  
//  eYo.forward('board')
//  
//  /**
//   * Shared application driver.
//   */
//  eYo.fcls.newDrvrC3s('Board')
//  
describe(`Inline tests at drvr/fcls/fcls_board.js`, function () {
  this.timeout(20000)
  beforeEach (function () { eYo.test.setup() })
  eYo.test.onrModel = eYo.NA
  eYo.test.setup()
  it(`eYo.fcls.Board`, function () {
    chai.assert(eYo.fcls.Board)
  })

})
