/**
 * edython
 *
 * Copyright 2018 Jérôme LAURENS.
 *
 * License EUPL-1.2
 */

/**
 * @fileoverview cmath model. Automatically generated by `bin/helpers/cmathbot.py cmath`
 * @author jerome.laurens@u-bourgogne.fr (Jérôme LAURENS)
 */
'use strict'

goog.provide('eYo.Model.cmath__module')

goog.require('eYo.Model')

eYo.Model.cmath__module.data = {
  prefix: 'cmath.',
  categories: [
    'conversions-to-and-from-polar-coordinates',
    'power-and-logarithmic-functions',
    'trigonometric-functions',
    'hyperbolic-functions',
    'classification-functions',
    'constants'
  ],
  types: [
    'function',
    'data'
  ],
  items: [
    {
      names: ['phase'],
      category: 0,
      type: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    },
    {
      names: ['polar'],
      category: 0,
      type: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    },
    {
      names: ['rect'],
      category: 0,
      type: 0,
      ary: 2,
      arguments: [
        {
          name: 'r'
        },
        {
          name: 'phi'
        }
      ]
    },
    {
      names: ['exp'],
      category: 1,
      type: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    },
    {
      names: ['log'],
      category: 1,
      type: 0,
      ary: 2,
      arguments: [
        {
          name: 'x'
        },
        {
          name: 'base'
        }
      ]
    },
    {
      names: ['log10'],
      category: 1,
      type: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    },
    {
      names: ['sqrt'],
      category: 1,
      type: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    },
    {
      names: ['acos'],
      category: 2,
      type: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    },
    {
      names: ['asin'],
      category: 2,
      type: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    },
    {
      names: ['atan'],
      category: 2,
      type: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    },
    {
      names: ['cos'],
      category: 2,
      type: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    },
    {
      names: ['sin'],
      category: 2,
      type: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    },
    {
      names: ['tan'],
      category: 2,
      type: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    },
    {
      names: ['acosh'],
      category: 3,
      type: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    },
    {
      names: ['asinh'],
      category: 3,
      type: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    },
    {
      names: ['atanh'],
      category: 3,
      type: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    },
    {
      names: ['cosh'],
      category: 3,
      type: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    },
    {
      names: ['sinh'],
      category: 3,
      type: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    },
    {
      names: ['tanh'],
      category: 3,
      type: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    },
    {
      names: ['isfinite'],
      category: 4,
      type: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    },
    {
      names: ['isinf'],
      category: 4,
      type: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    },
    {
      names: ['isnan'],
      category: 4,
      type: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    },
    {
      names: ['isclose'],
      category: 4,
      type: 0,
      ary: 5,
      mandatory: 3,
      arguments: [
        {
          name: 'a'
        },
        {
          name: 'b'
        },
        {
          name: '*'
        },
        {
          name: 'rel_tol',
          default: 1e-09
        },
        {
          name: 'abs_tol',
          default: 0.0
        }
      ]
    },
    {
      names: ['pi'],
      category: 5,
      type: 1
    },
    {
      names: ['e'],
      category: 5,
      type: 1
    },
    {
      names: ['tau'],
      category: 5,
      type: 1
    },
    {
      names: ['inf'],
      category: 5,
      type: 1
    },
    {
      names: ['infj'],
      category: 5,
      type: 1
    },
    {
      names: ['nan'],
      category: 5,
      type: 1
    },
    {
      names: ['nanj'],
      category: 5,
      type: 1
    }
  ],
  by_name: {
    'phase': 0,
    'polar': 1,
    'rect': 2,
    'exp': 3,
    'log': 4,
    'log10': 5,
    'sqrt': 6,
    'acos': 7,
    'asin': 8,
    'atan': 9,
    'cos': 10,
    'sin': 11,
    'tan': 12,
    'acosh': 13,
    'asinh': 14,
    'atanh': 15,
    'cosh': 16,
    'sinh': 17,
    'tanh': 18,
    'isfinite': 19,
    'isinf': 20,
    'isnan': 21,
    'isclose': 22,
    'pi': 23,
    'e': 24,
    'tau': 25,
    'inf': 26,
    'infj': 27,
    'nan': 28,
    'nanj': 29
  },
  by_category: {
    0: [0, 1, 2],
    1: [3, 4, 5, 6],
    2: [7, 8, 9, 10, 11, 12],
    3: [13, 14, 15, 16, 17, 18],
    4: [19, 20, 21, 22],
    5: [23, 24, 25, 26, 27, 28, 29]
  },
  by_type: {
    0: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
    1: [23, 24, 25, 26, 27, 28, 29]
  }
}

/**
 * Get the item with the given key
 * @param {!String|Number} key  The key or index of the item
 * @return {?Object} return the model object for that item, if any.
 */
eYo.Model.cmath__module.getItem = function (key) {
  if (!goog.isNumber(key)) {
    key = eYo.Model.cmath__module.data.by_name[key]
  }
  if (goog.isNumber(key)) {
    return eYo.Model.cmath__module.data.items[key]
  }
}

/**
 * Get the indices of the items for the given category
 * @param {!String} key  The name of the category
 * @return {!Array} the list of item indices with the given category (possibly void).
 */
eYo.Model.cmath__module.getItemsInCategory = function (category, type) {
  var ra = eYo.Model.cmath__module.data.by_category[category] || []
  if (goog.isString(type)) {
    type = eYo.Model.cmath__module.data.type.indexOf(type)
  }
  if (goog.isNumber(type) && type >= 0) {
    var ra2 = []
    for (var i = 0; i < ra.length ; i++ ) {
      var item = eYo.Model.cmath__module.getItem(i)
      if (item && item.type === type) {
        ra2.append(i)
      }
    }
    return ra2
  } else {
    return ra
  }
}

// This file was generated by `./bin/helpers/{module}bot.py` on 2018-07-12 12:49:33.948765


