/**
 * edython
 *
 * Copyright 2018 Jérôme LAURENS.
 *
 * License EUPL-1.2
 */

/**
 * @fileoverview math model. Automatically generated by `python3 bin/helpers/modulebot.py math`
 * @author jerome.laurens@u-bourgogne.fr (Jérôme LAURENS)
 */
'use strict'

goog.provide('eYo.Model.math__module')
goog.provide('eYo.Model.math__module.Item')

goog.require('eYo.Model')
goog.require('eYo.Model.Item')

/**
 * @constructor
 * @param {*} model 
 */
eYo.Model.math__module.Item = function (model) {
  eYo.Model.math__module.Item.superClass_.constructor.call(this, model)
}

var Item = eYo.Model.math__module.Item

goog.inherits(Item, eYo.Model.Item)

/**
 * model
 */
Item.prototype.model = eYo.Model.math__module


eYo.Model.math__module.data = {
  categories: [
    'number-theoretic-and-representation-functions',
    'power-and-logarithmic-functions',
    'trigonometric-functions',
    'angular-conversion',
    'hyperbolic-functions',
    'special-functions',
    'constants'
  ],
  types: [
    'function',
    'data'
  ],
  items: [
    new Item({
      name: 'ceil',
      class: 'math',
      category: 0,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'copysign',
      class: 'math',
      category: 0,
      type_: 0,
      ary: 2,
      arguments: [
        {
          name: 'x'
        },
        {
          name: 'y'
        }
      ]
    }),
    new Item({
      name: 'fabs',
      class: 'math',
      category: 0,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'factorial',
      class: 'math',
      category: 0,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'floor',
      class: 'math',
      category: 0,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'fmod',
      class: 'math',
      category: 0,
      type_: 0,
      ary: 2,
      arguments: [
        {
          name: 'x'
        },
        {
          name: 'y'
        }
      ]
    }),
    new Item({
      name: 'frexp',
      class: 'math',
      category: 0,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'fsum',
      class: 'math',
      category: 0,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'iterable'
        }
      ]
    }),
    new Item({
      name: 'gcd',
      class: 'math',
      category: 0,
      type_: 0,
      ary: 2,
      arguments: [
        {
          name: 'a'
        },
        {
          name: 'b'
        }
      ]
    }),
    new Item({
      name: 'isclose',
      class: 'math',
      category: 0,
      type_: 0,
      ary: Infinity,
      mandatory: 3,
      arguments: [
        {
          name: 'a'
        },
        {
          name: 'b'
        },
        {
          name: '*'
        },
        {
          name: 'rel_tol',
          default: 1e-09
        },
        {
          name: 'abs_tol',
          default: 0.0
        }
      ]
    }),
    new Item({
      name: 'isfinite',
      class: 'math',
      category: 0,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'isinf',
      class: 'math',
      category: 0,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'isnan',
      class: 'math',
      category: 0,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'ldexp',
      class: 'math',
      category: 0,
      type_: 0,
      ary: 2,
      arguments: [
        {
          name: 'x'
        },
        {
          name: 'i'
        }
      ]
    }),
    new Item({
      name: 'modf',
      class: 'math',
      category: 0,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'trunc',
      class: 'math',
      category: 0,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'exp',
      class: 'math',
      category: 1,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'expm1',
      class: 'math',
      category: 1,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'log',
      class: 'math',
      category: 1,
      type_: 0,
      ary: 2,
      mandatory: 1,
      arguments: [
        {
          name: 'x'
        },
        {
          name: 'base',
          optional: true
        }
      ]
    }),
    new Item({
      name: 'log1p',
      class: 'math',
      category: 1,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'log2',
      class: 'math',
      category: 1,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'log10',
      class: 'math',
      category: 1,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'pow',
      class: 'math',
      category: 1,
      type_: 0,
      ary: 2,
      arguments: [
        {
          name: 'x'
        },
        {
          name: 'y'
        }
      ]
    }),
    new Item({
      name: 'sqrt',
      class: 'math',
      category: 1,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'acos',
      class: 'math',
      category: 2,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'asin',
      class: 'math',
      category: 2,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'atan',
      class: 'math',
      category: 2,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'atan2',
      class: 'math',
      category: 2,
      type_: 0,
      ary: 2,
      arguments: [
        {
          name: 'y'
        },
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'cos',
      class: 'math',
      category: 2,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'hypot',
      class: 'math',
      category: 2,
      type_: 0,
      ary: 2,
      arguments: [
        {
          name: 'x'
        },
        {
          name: 'y'
        }
      ]
    }),
    new Item({
      name: 'sin',
      class: 'math',
      category: 2,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'tan',
      class: 'math',
      category: 2,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'degrees',
      class: 'math',
      category: 3,
      type_: 0,
      stmt: true,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'radians',
      class: 'math',
      category: 3,
      type_: 0,
      stmt: true,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'acosh',
      class: 'math',
      category: 4,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'asinh',
      class: 'math',
      category: 4,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'atanh',
      class: 'math',
      category: 4,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'cosh',
      class: 'math',
      category: 4,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'sinh',
      class: 'math',
      category: 4,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'tanh',
      class: 'math',
      category: 4,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'erf',
      class: 'math',
      category: 5,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'erfc',
      class: 'math',
      category: 5,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'gamma',
      class: 'math',
      category: 5,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'lgamma',
      class: 'math',
      category: 5,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'pi',
      category: 6,
      type_: 1,
      stmt: true
    }),
    new Item({
      name: 'e',
      category: 6,
      type_: 1,
      stmt: true
    }),
    new Item({
      name: 'tau',
      category: 6,
      type_: 1,
      stmt: true
    }),
    new Item({
      name: 'inf',
      category: 6,
      type_: 1,
      stmt: true
    }),
    new Item({
      name: 'nan',
      category: 6,
      type_: 1,
      stmt: true
    })
  ],
  by_name: {
    'isnan': 12,
    'log10': 21,
    'tan': 31,
    'isfinite': 10,
    'copysign': 1,
    'isclose': 9,
    'fmod': 5,
    'pi': 44,
    'erf': 40,
    'frexp': 6,
    'tau': 46,
    'hypot': 29,
    'exp': 16,
    'trunc': 15,
    'atanh': 36,
    'lgamma': 43,
    'asinh': 35,
    'fabs': 2,
    'e': 45,
    'gcd': 8,
    'fsum': 7,
    'log': 18,
    'gamma': 42,
    'degrees': 32,
    'atan2': 27,
    'asin': 25,
    'sin': 30,
    'isinf': 11,
    'acos': 24,
    'log1p': 19,
    'expm1': 17,
    'ceil': 0,
    'factorial': 3,
    'modf': 14,
    'radians': 33,
    'log2': 20,
    'erfc': 41,
    'acosh': 34,
    'tanh': 39,
    'nan': 48,
    'cosh': 37,
    'ldexp': 13,
    'floor': 4,
    'sinh': 38,
    'sqrt': 23,
    'cos': 28,
    'pow': 22,
    'inf': 47,
    'atan': 26
  },
  by_category: {
    2: [24, 25, 26, 27, 28, 29, 30, 31],
    5: [40, 41, 42, 43],
    3: [32, 33],
    1: [16, 17, 18, 19, 20, 21, 22, 23],
    0: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    4: [34, 35, 36, 37, 38, 39],
    6: [44, 45, 46, 47, 48]
  },
  by_type: {
    0: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
    1: [44, 45, 46, 47, 48]
  }
}
/**
 * Get the item with the given key
 * @param {!String|Number} key  The key or index of the item
 * @return {?Object} return the model object for that item, if any.
 */
eYo.Model.math__module.getItem = function (key) {
  if (!goog.isNumber(key)) {
    key = eYo.Model.math__module.data.by_name[key]
  }
  if (goog.isNumber(key)) {
    return eYo.Model.math__module.data.items[key]
  }
}

/**
 * Get the type of the given item.
 * @param {!Object} item.
 * @return {?String} return the type.
 */
eYo.Model.math__module.getType = function (item) {
  return item && item.type && eYo.Model.math__module.data.types[item.type]
}

/**
 * Get the indices of the items for the given category
 * @param {!String} key  The name of the category
 * @return {!Array} the list of item indices with the given category (possibly void).
 */
eYo.Model.math__module.getItemsInCategory = function (category, type) {
  var ra = eYo.Model.math__module.data.by_category[category] || []
  if (goog.isString(type)) {
    type = eYo.Model.math__module.data.type.indexOf(type)
  }
  if (goog.isNumber(type) && type >= 0) {
    var ra2 = []
    for (var i = 0; i < ra.length ; i++ ) {
      var item = eYo.Model.math__module.getItem(i)
      if (item && item.type === type) {
        ra2.append(i)
      }
    }
    return ra2
  } else {
    return ra
  }
}

// This file was generated by `python3 ./bin/helpers/modulebot.py math` on 2018-10-21 13:44:35.833036


