describe ('Tests: Observe', function () {
  this.timeout(20000)
  beforeEach (function () { eYo.test.setup() })
  eYo.test.setup()
  it (`$this`, function () {
    let ns = eYo.c3s.newNS()
    ns.makeBaseC3s()
    ns.BaseC3s[eYo.$].observeEnhanced()
    let o = ns.new()
    let oo = {
      flag(...$) {
        eYo.flag.push('/', ...$)
      }
    }
    o.addObserver(eYo.observe.BEFORE, oo, function (kv) {
      this.flag('b', kv)
    })
    o.willChange(eYo.test.kv)
    eYo.flag.expect('/b$kv')
  })
  it (`Inherited`, function () {
    let ns = eYo.c3s.newNS()
    let SuperC3s = ns.makeBaseC3s()
    let C3s = SuperC3s[eYo.$newSubC3s]('Foo')
    let ChildC3s = C3s[eYo.$newSubC3s]('Bar')
    SuperC3s[eYo.$].observeEnhanced()
    let o = new ChildC3s()
    let o_o = o.addObserver(eYo.observe.BEFORE, function (...$) {
      eYo.flag.push('1', ...$)
    })
    o.willChange(eYo.test.kv)
    eYo.flag.expect('1$kv')
    let o_ChildC3s = ChildC3s.prototype.addObserver(eYo.observe.BEFORE, function (...$) {
      eYo.flag.push('2', ...$)
    })
    o.willChange(eYo.test.kv)
    eYo.flag.expect('2$kv1$kv')
    let o_C3s = C3s.prototype.addObserver(eYo.observe.BEFORE, function (...$) {
      eYo.flag.push('3', ...$)
    })
    o.willChange(eYo.test.kv)
    eYo.flag.expect('3$kv2$kv1$kv')
    let o_SuperC3s = SuperC3s.prototype.addObserver(eYo.observe.BEFORE, function (...$) {
      eYo.flag.push(4, ...$)
    })
    o.willChange(eYo.test.kv)
    eYo.flag.expect('4$kv3$kv2$kv1$kv')
    o.removeObserver(o_o)
    o.willChange(eYo.test.kv)
    eYo.flag.expect('4$kv3$kv2$kv')
    ChildC3s.prototype.removeObserver(o_ChildC3s)
    o.willChange(eYo.test.kv)
    eYo.flag.expect('4$kv3$kv')
    C3s.prototype.removeObserver(o_C3s)
    o.willChange(eYo.test.kv)
    eYo.flag.expect('4$kv')
    SuperC3s.prototype.removeObserver(o_SuperC3s)
    o.willChange(eYo.test.kv)
    eYo.flag.expect()
  })
  it (`Shared and inherited`, function () {
    let ns = eYo.c3s.newNS()
    ns.makeBaseC3s()
    ns.BaseC3s[eYo.$].observeEnhanced()
    ns.new().willChange(eYo.test.kv)
    eYo.flag.expect()
    ns.BaseC3s_p.addObserver(eYo.observe.BEFORE, function (...$) {
      eYo.flag.push('o', ...$)
    })
    ns.new().willChange(eYo.test.kv)
    eYo.flag.expect('o$kv')
    ns.new().willChange(eYo.test.kv)
    eYo.flag.expect('o$kv')
  })
})
