// This file was generated by "update.py" on 2020-09-26 09:37:50.611637

//  /**
//   * @fileoverview eYo.shared is a namespace to collect singletons.
//   * @author jerome.laurens@u-bourgogne.fr (Jérôme LAURENS)
//   */
//  'use strict'
//  
//  eYo.require('c3s')
//  
//  // ANCHOR eYo.shared
//  /**
//   * @name{eYo.attr}
//   * @namespace
//   */
//  eYo.newNS('shared', {
//    OWNER: eYo.c3s.new(),
//  })
describe(`Inline tests at core/shared/shared.js`, function () {
  this.timeout(20000)
  beforeEach (function () { eYo.test.setup() })
  eYo.test.onrModel = eYo.NA
  eYo.test.setup()
  it(`Basics`, function () {
    chai.assert(eYo.shared)
    chai.expect(eYo.shared.OWNER).instanceof(eYo.c3s.BaseC3s)
  })

})
