/**
 * edython
 *
 * Copyright 2018 Jérôme LAURENS.
 *
 * License EUPL-1.2
 */

/**
 * @fileoverview heapq model. Automatically generated by `python3 bin/helpers/modulebot.py heapq`
 * @author jerome.laurens@u-bourgogne.fr (Jérôme LAURENS)
 */
'use strict'

goog.provide('eYo.Model.heapq__module')
goog.provide('eYo.Model.heapq__module.Item')

goog.require('eYo.Model')
goog.require('eYo.Model.Module')
goog.require('eYo.Model.Item')

eYo.Model.heapq__module = new eYo.Model.Module('heapq__module', 'https://docs.python.org/3.6/library/heapq.html')

/**
 * @constructor
 * @param {*} model
 */
eYo.Model.heapq__module.Item = function (model) {
  eYo.Model.heapq__module.Item.superClass_.constructor.call(this, model)
}

var doit = (() => {

var Item = eYo.Model.heapq__module.Item

goog.inherits(Item, eYo.Model.Item)

/**
 * module
 */
Item.prototype.module = eYo.Model.heapq__module

Object.defineProperties(
  Item.prototype,
  {
    url: {
      get() {
        return this.href
          ? this.module.url + this.href
          : this.module.url
      }
    }
  }
)

eYo.Model.heapq__module.setData({
  categories: [
    'module-heapq'
  ],
  types: [
    'function'
  ],
  items: [
    new Item({
      name: 'heapify',
      class: 'heapq',
      category: 0,
      type_: 0,
      href: '#heapq.heapify',
      stmt: true,
      ary: 1,
      arguments: [
        {
          name: 'x'
        }
      ]
    }),
    new Item({
      name: 'heappop',
      class: 'heapq',
      category: 0,
      type_: 0,
      href: '#heapq.heappop',
      ary: 1,
      arguments: [
        {
          name: 'heap'
        }
      ]
    }),
    new Item({
      name: 'heappush',
      class: 'heapq',
      category: 0,
      type_: 0,
      href: '#heapq.heappush',
      stmt: true,
      ary: 2,
      arguments: [
        {
          name: 'heap'
        },
        {
          name: 'item'
        }
      ]
    }),
    new Item({
      name: 'heappushpop',
      class: 'heapq',
      category: 0,
      type_: 0,
      href: '#heapq.heappushpop',
      ary: 2,
      arguments: [
        {
          name: 'heap'
        },
        {
          name: 'item'
        }
      ]
    }),
    new Item({
      name: 'heapreplace',
      class: 'heapq',
      category: 0,
      type_: 0,
      href: '#heapq.heapreplace',
      ary: 2,
      arguments: [
        {
          name: 'heap'
        },
        {
          name: 'item'
        }
      ]
    }),
    new Item({
      name: 'merge',
      class: 'heapq',
      category: 0,
      type_: 0,
      href: '#heapq.merge',
      ary: Infinity,
      mandatory: 0,
      arguments: [
        {
          name: '*iterables',
          optional: true
        },
        {
          name: 'key',
          default: 'None'
        },
        {
          name: 'reverse',
          default: 'False'
        }
      ]
    }),
    new Item({
      name: 'nlargest',
      class: 'heapq',
      category: 0,
      type_: 0,
      href: '#heapq.nlargest',
      ary: 3,
      mandatory: 2,
      arguments: [
        {
          name: 'n'
        },
        {
          name: 'iterable'
        },
        {
          name: 'key',
          default: 'None'
        }
      ]
    }),
    new Item({
      name: 'nsmallest',
      class: 'heapq',
      category: 0,
      type_: 0,
      href: '#heapq.nsmallest',
      ary: 3,
      mandatory: 2,
      arguments: [
        {
          name: 'n'
        },
        {
          name: 'iterable'
        },
        {
          name: 'key',
          default: 'None'
        }
      ]
    })
  ],
  by_name: {
    'heapify': 0,
    'heappop': 1,
    'heappush': 2,
    'heappushpop': 3,
    'heapreplace': 4,
    'merge': 5,
    'nlargest': 6,
    'nsmallest': 7
  },
  by_category: {
    0: [0, 1, 2, 3, 4, 5, 6, 7]
  },
  by_type: {
    0: [0, 1, 2, 3, 4, 5, 6, 7]
  }
})


})()


// This file was generated by `python3 ./bin/helpers/modulebot.py heapq` on 2019-05-07 08:48:06.075815


