/**
 * edython
 *
 * Copyright 2018 Jérôme LAURENS.
 *
 * License EUPL-1.2
 */

/**
 * @fileoverview statistics model. Automatically generated by `python3 bin/helpers/modulebot.py statistics`
 * @author jerome.laurens@u-bourgogne.fr (Jérôme LAURENS)
 */
'use strict'

goog.provide('eYo.Model.statistics__module')
goog.provide('eYo.Model.statistics__module.Item')

goog.require('eYo.Model')
goog.require('eYo.Model.Item')

/**
 * @constructor
 * @param {*} model 
 */
eYo.Model.statistics__module.Item = function (model) {
  eYo.Model.statistics__module.Item.superClass_.constructor.call(this, model)
}

var Item = eYo.Model.statistics__module.Item

goog.inherits(Item, eYo.Model.Item)

/**
 * model
 */
Item.prototype.model = eYo.Model.statistics__module


eYo.Model.statistics__module.data = {
  categories: [
    'function-details',
    'exceptions'
  ],
  types: [
    'function',
    'exception'
  ],
  items: [
    new Item({
      name: 'mean',
      class: 'statistics',
      category: 0,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'data'
        }
      ]
    }),
    new Item({
      name: 'harmonic_mean',
      class: 'statistics',
      category: 0,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'data'
        }
      ]
    }),
    new Item({
      name: 'median',
      class: 'statistics',
      category: 0,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'data'
        }
      ]
    }),
    new Item({
      name: 'median_low',
      class: 'statistics',
      category: 0,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'data'
        }
      ]
    }),
    new Item({
      name: 'median_high',
      class: 'statistics',
      category: 0,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'data'
        }
      ]
    }),
    new Item({
      name: 'median_grouped',
      class: 'statistics',
      category: 0,
      type_: 0,
      ary: 2,
      mandatory: 1,
      arguments: [
        {
          name: 'data'
        },
        {
          name: 'interval',
          default: 1
        }
      ]
    }),
    new Item({
      name: 'mode',
      class: 'statistics',
      category: 0,
      type_: 0,
      ary: 1,
      arguments: [
        {
          name: 'data'
        }
      ]
    }),
    new Item({
      name: 'pstdev',
      class: 'statistics',
      category: 0,
      type_: 0,
      ary: 2,
      mandatory: 1,
      arguments: [
        {
          name: 'data'
        },
        {
          name: 'mu',
          default: 'None'
        }
      ]
    }),
    new Item({
      name: 'pvariance',
      class: 'statistics',
      category: 0,
      type_: 0,
      ary: 2,
      mandatory: 1,
      arguments: [
        {
          name: 'data'
        },
        {
          name: 'mu',
          default: 'None'
        }
      ]
    }),
    new Item({
      name: 'stdev',
      class: 'statistics',
      category: 0,
      type_: 0,
      ary: 2,
      mandatory: 1,
      arguments: [
        {
          name: 'data'
        },
        {
          name: 'xbar',
          default: 'None'
        }
      ]
    }),
    new Item({
      name: 'variance',
      class: 'statistics',
      category: 0,
      type_: 0,
      ary: 2,
      mandatory: 1,
      arguments: [
        {
          name: 'data'
        },
        {
          name: 'xbar',
          default: 'None'
        }
      ]
    }),
    new Item({
      name: 'StatisticsError',
      category: 1,
      type_: 1
    })
  ],
  by_name: {
    'median': 2,
    'harmonic_mean': 1,
    'median_grouped': 5,
    'pvariance': 8,
    'mean': 0,
    'variance': 10,
    'StatisticsError': 11,
    'pstdev': 7,
    'median_high': 4,
    'mode': 6,
    'stdev': 9,
    'median_low': 3
  },
  by_category: {
    0: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    1: [11]
  },
  by_type: {
    1: [11],
    0: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  }
}
/**
 * Get the item with the given key
 * @param {!String|Number} key  The key or index of the item
 * @return {?Object} return the model object for that item, if any.
 */
eYo.Model.statistics__module.getItem = function (key) {
  if (!goog.isNumber(key)) {
    key = eYo.Model.statistics__module.data.by_name[key]
  }
  if (goog.isNumber(key)) {
    return eYo.Model.statistics__module.data.items[key]
  }
}

/**
 * Get the type of the given item.
 * @param {!Object} item.
 * @return {?String} return the type.
 */
eYo.Model.statistics__module.getType = function (item) {
  return item && item.type && eYo.Model.statistics__module.data.types[item.type]
}

/**
 * Get the indices of the items for the given category
 * @param {!String} key  The name of the category
 * @return {!Array} the list of item indices with the given category (possibly void).
 */
eYo.Model.statistics__module.getItemsInCategory = function (category, type) {
  var ra = eYo.Model.statistics__module.data.by_category[category] || []
  if (goog.isString(type)) {
    type = eYo.Model.statistics__module.data.type.indexOf(type)
  }
  if (goog.isNumber(type) && type >= 0) {
    var ra2 = []
    for (var i = 0; i < ra.length ; i++ ) {
      var item = eYo.Model.statistics__module.getItem(i)
      if (item && item.type === type) {
        ra2.append(i)
      }
    }
    return ra2
  } else {
    return ra
  }
}

// This file was generated by `python3 ./bin/helpers/modulebot.py statistics` on 2018-10-23 13:34:46.940904


