/**
 * edython
 *
 * Copyright 2019 Jérôme LAURENS.
 *
 * License EUPL-1.2
 */

/**
 * @fileoverview statistics module. Automatically generated by `python3 bin/helpers/modulebot.py statistics through npm run eyo:module`
 * @author jerome.laurens@u-bourgogne.fr (Jérôme LAURENS)
 */
'use strict'

eYo.module.newNS('statistics__module', {
  URL: 'https://docs.python.org/3.6/library/statistics.html'
})

;(() => {
  /* Singleton constructor */
  let newItem = eYo.module.statistics__module.makeNewItem()

  eYo.module.statistics__module.data_ = {
    categories: [
      'function-details',
      'exceptions'
    ],
    types: [
      'function',
      'exception'
    ],
    items: [
      newItem({
        name: 'StatisticsError',
        class: 'statistics',
        category: 1,
        type_: 1,
        href: '#statistics.StatisticsError',
        ary: 0
      }),
      newItem({
        name: 'harmonic_mean',
        class: 'statistics',
        category: 0,
        type_: 0,
        href: '#statistics.harmonic_mean',
        ary: 1,
        arguments: [
          {
            name: 'data'
          }
        ]
      }),
      newItem({
        name: 'mean',
        class: 'statistics',
        category: 0,
        type_: 0,
        href: '#statistics.mean',
        ary: 1,
        arguments: [
          {
            name: 'data'
          }
        ]
      }),
      newItem({
        name: 'median',
        class: 'statistics',
        category: 0,
        type_: 0,
        href: '#statistics.median',
        ary: 1,
        arguments: [
          {
            name: 'data'
          }
        ]
      }),
      newItem({
        name: 'median_grouped',
        class: 'statistics',
        category: 0,
        type_: 0,
        href: '#statistics.median_grouped',
        ary: 2,
        mandatory: 1,
        arguments: [
          {
            name: 'data'
          },
          {
            name: 'interval',
            default: 1
          }
        ]
      }),
      newItem({
        name: 'median_high',
        class: 'statistics',
        category: 0,
        type_: 0,
        href: '#statistics.median_high',
        ary: 1,
        arguments: [
          {
            name: 'data'
          }
        ]
      }),
      newItem({
        name: 'median_low',
        class: 'statistics',
        category: 0,
        type_: 0,
        href: '#statistics.median_low',
        ary: 1,
        arguments: [
          {
            name: 'data'
          }
        ]
      }),
      newItem({
        name: 'mode',
        class: 'statistics',
        category: 0,
        type_: 0,
        href: '#statistics.mode',
        ary: 1,
        arguments: [
          {
            name: 'data'
          }
        ]
      }),
      newItem({
        name: 'pstdev',
        class: 'statistics',
        category: 0,
        type_: 0,
        href: '#statistics.pstdev',
        ary: 2,
        mandatory: 1,
        arguments: [
          {
            name: 'data'
          },
          {
            name: 'mu',
            default: 'None'
          }
        ]
      }),
      newItem({
        name: 'pvariance',
        class: 'statistics',
        category: 0,
        type_: 0,
        href: '#statistics.pvariance',
        ary: 2,
        mandatory: 1,
        arguments: [
          {
            name: 'data'
          },
          {
            name: 'mu',
            default: 'None'
          }
        ]
      }),
      newItem({
        name: 'stdev',
        class: 'statistics',
        category: 0,
        type_: 0,
        href: '#statistics.stdev',
        ary: 2,
        mandatory: 1,
        arguments: [
          {
            name: 'data'
          },
          {
            name: 'xbar',
            default: 'None'
          }
        ]
      }),
      newItem({
        name: 'variance',
        class: 'statistics',
        category: 0,
        type_: 0,
        href: '#statistics.variance',
        ary: 2,
        mandatory: 1,
        arguments: [
          {
            name: 'data'
          },
          {
            name: 'xbar',
            default: 'None'
          }
        ]
      })
    ],
    by_name: {
      'StatisticsError': 0,
      'harmonic_mean': 1,
      'mean': 2,
      'median': 3,
      'median_grouped': 4,
      'median_high': 5,
      'median_low': 6,
      'mode': 7,
      'pstdev': 8,
      'pvariance': 9,
      'stdev': 10,
      'variance': 11
    },
    by_category: {
      0: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
      1: [0]
    },
    by_type: {
      0: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
      1: [0]
    }
  }
  

}) ()


  // This file was generated by `python3 ./bin/helpers/modulebot.py statistics` on 2020-03-04 13:02:48.966071


